before_install:
  # decrypt rsa key:
- openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv
  -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
- chmod 0600 build/travis_ci_rsa
- cp build/travis_ci_rsa ~/.ssh/id_rsa
  # install deps:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:deadsnakes/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq default-jre
- sudo apt-get install -qq g++-7 gcc-7
- sudo apt-get install -qq doxygen graphviz
- sudo apt-get install -qq python3.7 python3-pip
- sudo python3.7 -m pip install --upgrade jinja2 Pygments

sudo: required
dist: xenial
language: cpp
compiler: g++
os: linux
script:
- export CC=gcc-7 CXX=g++-7 PYTHON=$(which python3.7)
- $PYTHON build/builder.py build
- $PYTHON build/builder.py doc
