before_install:
  # decrypt rsa key:
- openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv
  -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
- chmod 0600 build/travis_ci_rsa
- cp build/travis_ci_rsa ~/.ssh/id_rsa
  # install deps:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:deadsnakes/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq default-jre
- sudo apt-get install -qq clang-3.8
- sudo apt-get install -qq libgtest-dev
- git clone https://github.com/google/googletest.git
- cd googletest
- cmake .
- make
- cd lib
- sudo cp *.a /usr/lib
- sudo apt-get install -qq doxygen graphviz
- sudo apt-get install -qq python3.7 python3-pip
- sudo python3.7 -m pip install --upgrade jinja2 Pygments

sudo: required
dist: xenial
language: cpp
compiler: c++
os: linux
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- export CC=cc CXX=c++ PYTHON=$(which python3.7)
- $PYTHON build/builder.py build
- if [ "$BRANCH" == "master" ]; then
    $PYTHON build/builder.py doc;
    $PYTHON build/builder.py pubdoc;
  fi
