language: cpp

jobs:
    include:
        - os: linux
          env: BADGE=linux
          dist: focal
          addons:
            apt:
                update: true
                packages:
                - doxygen
                - graphviz
                - python3
                - python3-pip
                - cmake
                - wget
          before_install:
          - gpg --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
          - gpg --export --armor 16126D3A3E5C1192 | sudo apt-key add -
          - sudo apt-get update
          - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

        - os: osx
          env: BADGE=osx
          osx_image: xcode12
          addons:
            ssh_known_hosts: github.com
            homebrew:
                update: true
                packages:
                - doxygen
                - graphviz
                - python3
                - python3-pip
                - cmake
                - wget

install:
  # decrypt rsa key:
  - openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
  - chmod 0600 build/travis_ci_rsa
  - cp build/travis_ci_rsa ~/.ssh/id_rsa
  # install deps:
  - sudo python3 -m pip install --upgrade jinja2 Pygments

sudo: required
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- export CC=clang CXX=clang++ PYTHON=$(which python3)

- $PYTHON build/builder.py build
- if [ "$BRANCH" == "master" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
    $PYTHON build/builder.py doc;
    $PYTHON build/builder.py pubdoc;
  fi
