before_install:
  # decryption:
- openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv
  -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
- chmod 0600 build/travisci_rsa
- cp build/travisci_rsa ~/.ssh/id_rsa
  # install deps:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq default-jre
- sudo apt-get install -qq python3
- sudo apt-get install -qq g++-7
- sudo apt-get install -qq gcc-7
- sudo apt-get install -qq doxygen
- sudo apt-get install -qq graphviz

sudo: required
dist: trusty
language: cpp
compiler: g++
os: linux
script:
- export CC=gcc-7
- export CXX=g++-7
- python3 build/builder.py build
- python3 build/builder.py doc
