before_install:
- openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv
  -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
- chmod 0600 build/travis_ci_rsa
- cp build/travis_ci_rsa ~/.ssh/id_rsa
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq default-jre
- sudo apt-get install -qq g++-7 gcc-7
- sudo apt-get install -qq doxygen graphviz
sudo: required
dist: trusty
language: cpp
compiler: g++
os: linux
python: "3.6"
script:
python3 --version
- export CC=gcc-7
- export CXX=g++-7
- python3 build/builder.py build
- python3 build/builder.py doc
