before_install:
  # install deps:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq default-jre
- sudo apt-get install -qq python3
- sudo apt-get install -qq g++-7
- sudo apt-get install -qq gcc-7
- sudo apt-get install -qq doxygen
- sudo apt-get install -qq doxygen-doc
- sudo apt-get install -qq doxygen-latex
- sudo apt-get install -qq doxygen-gui
- sudo apt-get install -qq graphviz
- sudo apt-get install -qq openssl

sudo: required
dist: trusty
language: cpp
compiler: g++
os: linux
script:
  # decrypt key:
- openssl aes-256-cbc -K $encrypted_caa9910ca73e_key -iv $encrypted_caa9910ca73e_iv
  -in build/travisci_rsa.enc -out build/travisci_rsa -d
- chmod 0600 build/travisci_rsa
- cp build/travisci_rsa ~/.ssh/id_rsa

  # run builder:
- export CC=gcc-7
- export CXX=g++-7
- python3 build/builder.py build
- python3 build/builder.py doc
