language: cpp

addons:
    apt:
        update: true
        packages:
        - doxygen
        - graphviz
        - python3.7
        - python3-pip
        - cmake
        - wget

jobs:
    include:
        - os: linux
          dist: focal

before_install:
  # decrypt rsa key:
  - openssl aes-256-cbc -K $encrypted_9d345fbe8fd6_key -iv $encrypted_9d345fbe8fd6_iv -in build/travis_ci_rsa.enc -out build/travis_ci_rsa -d
  - chmod 0600 build/travis_ci_rsa
  - cp build/travis_ci_rsa ~/.ssh/id_rsa
  # install deps:
  - sudo python3.7 -m pip install --upgrade jinja2 Pygments
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  # googletest
  - cd external
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - make
  - cd lib
  - sudo cp ./*.a /usr/local/lib
  - cd ..
  - cd googletest/include
  - sudo mv gtest /usr/local/include
  - cd ../../../..

sudo: required
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- export CC=clang CXX=clang++ PYTHON=$(which python3.7)

- $PYTHON build/builder.py build
- if [ "$BRANCH" == "master" ]; then
    $PYTHON build/builder.py doc;
    $PYTHON build/builder.py pubdoc;
  fi
