name: CI for main

on:
  push:
    branches: [ feature-test-doxygen ]
  pull_request:
    branches: [ main ]

jobs:
  publish-doc:
    name: publish doc
    runs-on: ubuntu-22.04

    steps:
      - name: install native dependencies.
        run: |
          sudo apt install -y graphviz python3 python3-pip ruby rubygems wget cmake flex bison libclang-dev

      - name: install doxygen 1.9.2 source
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_2/doxygen-1.9.2.src.tar.gz
          tar -xzf doxygen-1.9.2.src.tar.gz
          cd doxygen-1.9.2
          cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          sudo make install
          doxygen --version

      - name: install python dependencies.
        run: sudo python3 -m pip install --upgrade jinja2 Pygments

      - name: install gems.
        run: sudo gem install jekyll bundler

      - name: checkout master codes.
        uses: actions/checkout@v4

      - name: commit docs if it's different to previous commit
        run: |
          export C=clang CXX=clang++ PYTHON=$(which python3)
          sudo $PYTHON ${{github.workspace}}/build/builder.py doc
          sudo $PYTHON ${{github.workspace}}/build/builder.py pubdoc

      - name: push the commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: ${{github.workspace}}/build/html
          repository: byeolang/website
          github_token: ${{secrets.PAT_TOKEN}}
          branch: 'main'
