name: CI for stable

on:
  push:
    branches: [ stable ]

jobs:
  build-on-linux:
    name: build on linux
    runs-on: ubuntu-latest

    steps:
    - name: install native dependencies.
      run: |
        sudo apt install python3 python3-pip cmake wget flex graphviz
        ls .
        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
        tar -zxvf bison-3.8.2.tar.gz
        cd bison-3.8.2
        ./configure
        sudo make
        sudo make install
        cd ..
        sudo rm -rf bison-3.8.2
        sudo mv /usr/bin/bison /usr/bin/bison-prev
        sudo ln -s /usr/local/bin/bison /usr/bin/bison


    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: build & test current codes.
      run: |
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/swrd/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py rel
        sudo $PYTHON ${{github.workspace}}/build/builder.py test

    - name: upload output files.
      uses: actions/upload-artifact@v3
      with:
        name: wrd-release-ubuntu
        path: ${{github.workspace}}/bin/

  build-on-macos:
    name: build on macos
    runs-on: macos-latest

    steps:
    - name: install native dependencies.
      run: |
        brew update
        brew install python3 cmake wget bison flex graphviz

    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: build & test current codes.
      run: |
        export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/swrd/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py rel
        sudo $PYTHON ${{github.workspace}}/build/builder.py test

    - name: upload output files.
      uses: actions/upload-artifact@v3
      with:
        name: wrd-release-macos
        path: ${{github.workspace}}/bin/
