name: CI for stable

on:
  push:
    branches: [ stable ]

jobs:
  checking-code-format:
    name: check code format with clang-format
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path:
          - check: 'mod'
            exclude: '(seedlingParser|seedlingScanner|lowparser|lowscanner)'
    steps:
    - uses: actions/checkout@v4
    - name: run clang-format to verify current codes.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}

  release-on-linux:
    needs: [checking-code-format]
    name: release on linux
    runs-on: ubuntu-22.04

    steps:
    - name: install native dependencies.
      run: |
        sudo apt-get update
        sudo apt install python3 python3-pip cmake wget flex graphviz clang-format clang-tidy
        ls .
        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
        tar -zxvf bison-3.8.2.tar.gz
        cd bison-3.8.2
        ./configure
        sudo make
        sudo make install
        cd ..
        sudo rm -rf bison-3.8.2
        sudo mv /usr/bin/bison /usr/bin/bison-prev
        sudo ln -s /usr/local/bin/bison /usr/bin/bison

    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: make deb file
      run: |
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/leaf/parser/bison
        sudo $PYTHON ${{github.workspace}}/build/builder.py pub deb
        sudo $PYTHON ${{github.workspace}}/build/builder.py test

    - name: upload output files.
      uses: actions/upload-artifact@v3
      with:
        name: namu-release-ubuntu
        path: ${{github.workspace}}/bin/namu-*-release.deb

    - name: make wasm file
      run: |
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/seedling/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py wasm

    - name: upload wasm file
      uses: actions/upload-artifact@v3
      with:
        name: namu-release-wasm
        path: |
          ${{github.workspace}}/bin/namu.js
          ${{github.workspace}}/bin/namu.wasm

  release-on-macos:
    needs: [checking-code-format]
    name: release on macos
    runs-on: macos-13

    steps:
    - name: install native dependencies.
      run: |
        brew unlink python && brew link --overwrite python
        brew install cmake wget bison flex graphviz llvm
        ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"

    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: build & test current codes.
      run: |
        export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/seedling/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py rel
        sudo $PYTHON ${{github.workspace}}/build/builder.py test
        sudo $PYTHON ${{github.workspace}}/build/builder.py pub mac

    - name: archive to tar files
      run: tar -cvf namu-release-macos.tar ${{github.workspace}}/bin/

    - name: upload output files.
      uses: actions/upload-artifact@v3
      with:
        name: namu-release-macos
        path: namu-release-macos.tar

  release-on-windows:
    needs: [checking-code-format]
    name: release on windows
    runs-on: windows-latest

    steps:
    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: install apps from choco
      uses: crazy-max/ghaction-chocolatey@v2.0.0
      with:
        args: install -y wget unzip zip

    - name: get flex_bison for windows & unzip
      run: |
        mkdir ${{github.workspace}}\flex_bison
        wget -O flex_bison\flex_bison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip
        cd flex_bison
        unzip flex_bison.zip
        ren win_flex.exe flex.exe
        ren win_bison.exe bison.exe
        $env:PATH = "$env:PATH;${{github.workspace}}\flex_bison"
        echo $env:PATH
        python ${{github.workspace}}\build\builder.py pub win

    - name: archives to zip file
      run: |
        zip -9vr namu-release-win.zip ${{github.workspace}}\bin

    - name: upload output files.
      uses: actions/upload-artifact@v3
      with:
        name: namu-release-win
        path: namu-release-win.zip
