name: CI for master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-linux:
    name: build on linux
    runs-on: ubuntu-latest

    steps:
    - name: install native dependencies.
      run: sudo apt install python3 python3-pip cmake wget bison flex graphviz

    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: build & test current codes.
      run: |
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/swrd/src/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py dbg

  build-on-macos:
    name: build on macos
    runs-on: macos-latest

    steps:
    - name: install native dependencies.
      run: |
        brew update
        brew install python3 cmake wget bison flex graphviz

    - name: checkout repository codes
      uses: actions/checkout@v2

    - name: build & test current codes.
      run: |
        export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        export C=clang CXX=clang++ PYTHON=$(which python3)
        ls -l ${{github.workspace}}/mod/swrd/src/parser
        sudo $PYTHON ${{github.workspace}}/build/builder.py dbg

  publish-doc:
    needs: [build-on-linux, build-on-macos]
    name: publish doc
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository codes
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: install native dependencies.
        run: sudo apt install doxygen graphviz python3 python3-pip

      - name: install python dependencies.
        run: sudo python3 -m pip install --upgrade jinja2 Pygments

      - name: commit docs if it's different to previous commit
        run: |
          export C=clang CXX=clang++ PYTHON=$(which python3)
          sudo $PYTHON ${{github.workspace}}/build/builder.py doc
          sudo $PYTHON ${{github.workspace}}/build/builder.py pubdoc

      - name: test
        working-directory: 4{{github.workspace}}/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -l .
          git status
          git branch
          echo $GITHUB_TOKEN

      - name: push the commit
        working-directory: ${{github.workspace}}/build/html
        uses: ad-m/github-push-action@master
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{ github.ref}}
